version: '3.8'

services:
  fp:
    image: luischua/fp
    ports:
      - target: 8800
        published: 8080
        protocol: tcp
        mode: host
    links:
      - "couchdb"
    environment:
      - JAVA_OPTIONS='-Xmx512m'
      - PROPERTIES_FILENAME=fp
    volumes:
      - type: bind
        source: C:\Users\Brookfield\Downloads\fp_config
        target: /config
      - type: bind
        source: C:\Users\Brookfield\Downloads\fp_logs
        target: /logs
  couchdb:
    image: couchdb
    ports:
      - target: 5984
        published: 5900
        protocol: tcp
        mode: host
    env_file:
      - ./db.properties
    volumes:
      - type: bind
        source: C:\Users\Brookfield\Downloads\couchdb_data
        target: /opt/couchdb/data
      - type: bind
        source: C:\Users\Brookfield\Downloads\couchdb_config
        target: /opt/couchdb/etc/local.d
      - type: bind
        source: C:\Users\Brookfield\Downloads\couchdb_logs
        target: /opt/couchdb/log